/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStyleProvider: typeof import('ant-design-vue/es')['StyleProvider']
    Busy: typeof import('./src/components/Busy.vue')['default']
    DrawerUserCenter: typeof import('./src/components/DrawerUserCenter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ModaInviteQRCode: typeof import('./src/components/ModaInviteQRCode.vue')['default']
    ModalClaimWeekRewards: typeof import('./src/components/ModalClaimWeekRewards.vue')['default']
    ModalEmotionCamera: typeof import('./src/components/ModalEmotionCamera.vue')['default']
    ModalJunVideo: typeof import('./src/components/ModalJunVideo.vue')['default']
    ModalPrivacyAgreement: typeof import('./src/components/ModalPrivacyAgreement.vue')['default']
    ModalTarotParse: typeof import('./src/components/ModalTarotParse.vue')['default']
    ModalUploadedRating: typeof import('./src/components/ModalUploadedRating.vue')['default']
    ModalWallets: typeof import('./src/components/ModalWallets.vue')['default']
    ModaPayPortfolio: typeof import('./src/components/ModaPayPortfolio.vue')['default']
    RootDefault: typeof import('./src/components/RootDefault.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialLink: typeof import('./src/components/SocialLink.vue')['default']
    TelegramLoginWidget: typeof import('./src/components/TelegramLoginWidget.vue')['default']
    WalletAccountPanel: typeof import('./src/components/WalletAccountPanel.vue')['default']
    WalletEvmAccountPanel: typeof import('./src/components/WalletEvmAccountPanel.vue')['default']
  }
}
