// Logo
// export * as iLogoStandard from '../assets/logo/standard.svg'
export * as iLogoStandardMark from '../assets/logo/standard-mark.svg'

// Base
export * as iClose from '../assets/base/close.svg'
export * as iUpload from '../assets/base/upload.svg'
export * as iMenu from '../assets/base/menu.svg'
export * as iMenuCircle from '../assets/base/menu-circle.svg'
export * as iAvatar from '../assets/base/avatar.svg'
export * as iLogOut from '../assets/base/log-out.svg'
export * as iArrowRight from  '../assets/base/arrow-right.svg'
export * as iInfoCircle  from  '../assets/base/info-circle.svg'
export * as iFlag from  '../assets/base/flag.svg'
export * as iMoreHCircle from  '../assets/base/more-h-circle.svg'
export * as iQuestionCircle from  '../assets/base/question-circle.svg'
export * as iSend from  '../assets/base/send.svg'
export * as iPaperclip from  '../assets/base/paperclip.svg'
export * as iHeart from  '../assets/base/heart.svg'
export * as iLink from  '../assets/base/link.svg'
export * as iImage from  '../assets/base/image.svg'
export * as iHome from  '../assets/base/home.svg'
export * as iSlidersH from  '../assets/base/sliders-h.svg'
export * as iX from  '../assets/base/x.svg'
export * as iTelegram from  '../assets/base/telegram.svg'
export * as iGitbook from  '../assets/base/gitbook.svg'
export * as iUser from '../assets/base/user.svg'
export * as iTimesSquare from '../assets/base/times-square.svg'
export * as iSettings from '../assets/base/settings.svg'
export * as iPlusSquare from '../assets/base/plus-square.svg'
export * as iGlobe from '../assets/base/globe.svg'
export * as iChevronCircleDown from '../assets/base/chevron-circle-down.svg'
export * as iCheckCircle from '../assets/base/check-circle.svg'
export * as iQRCode from '../assets/base/qr-code.svg'
export * as iCopy from '../assets/base/copy.svg'
export * as iTablet from '../assets/base/tablet.svg'
export * as iScore from '../assets/base/score.svg'
export * as iTarot from '../assets/base/tarot.svg'
export * as iShare from '../assets/base/share.svg'
export * as iCamera from '../assets/base/camera.svg'
export * as iChevronUp from '../assets/base/chevron-up.svg'
export * as iShutter from '../assets/base/shutter.svg'
export * as iChevronLeft from '../assets/base/chevron-left.svg'
export * as iWatch from '../assets/base/watch.svg'

// View
export * as iViewUploadPhoto from '../assets/view/emotion/upload-photo.svg'

// Emoji
export * as iAngryActive from '../assets/emoji/active/angry.svg'
export * as iCalmActive from '../assets/emoji/active/calm.svg'
export * as iConfusedActive from '../assets/emoji/active/confused.svg'
export * as iDisgustedActive from '../assets/emoji/active/disgusted.svg'
export * as iFearActive from '../assets/emoji/active/fear.svg'
export * as iHappyActive from '../assets/emoji/active/happy.svg'
export * as iSadActive from '../assets/emoji/active/sad.svg'
export * as iSurprisedActive from '../assets/emoji/active/surprised.svg'
export * as iUnknownActive from '../assets/emoji/active/unknown.svg'
export * as iAngryDefault from '../assets/emoji/default/angry.svg'
export * as iCalmDefault from '../assets/emoji/default/calm.svg'
export * as iConfusedDefault from '../assets/emoji/default/confused.svg'
export * as iDisgustedDefault from '../assets/emoji/default/disgusted.svg'
export * as iFearDefault from '../assets/emoji/default/fear.svg'
export * as iHappyDefault from '../assets/emoji/default/happy.svg'
export * as iSadDefault from '../assets/emoji/default/sad.svg'
export * as iSurprisedDefault from '../assets/emoji/default/surprised.svg'
export * as iUnknownDefault from '../assets/emoji/default/unknown.svg'

// Art
export * as iNoData from '../assets/art/no-data.svg'

// Icon
export * as iIconJun from '../assets/coin/jun.svg'
export * as iUSDT from '../assets/coin/usdt.svg'